spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.20.232:3306/sys?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC #mysql8
    username: root
    password: root@1109

  aop:
    proxy-target-class: true

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss #mvc接收参数时对日期进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #jackson对响应回去的日期参数进行格式化
    time-zone: GMT+8

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8